export const LEVEL_ANSWERS = {
  1: [
    {//""
      correct: "00",
      answers: {
        1: "00",
        2: "10",
        3: "01",
        0: "11",
      },
      wrongMappings: {
        1: 1,
        2: 2,
        3: 3,
        0: 0,
      },
      rightMapping: 1,
      variant: "",
    },
    {//"B"
      correct: "0",
      answers: {
        1: "00",
        2: "0",
        3: "1",
        0: "11",
      },
      wrongMappings: {
        1: 1,
        2: 2,
        3: 3,
        0: 0,
      },
      rightMapping: 2,
      variant: "B",
    },
    {//"C"
      correct: "100",
      answers: {
        1: "001",
        2: "101",
        3: "010",
        0: "100",
      },
      wrongMappings: {
        1: 1,
        2: 2,
        3: 3,
        0: 0,
      },
      rightMapping: 0,
      variant: "C"
    },
  ],
  2: [{//""
    correct: "110",
    answers: {
      1: "010",
      2: "110",
      3: "001",
      0: "111",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 1,
  },{//"B"
    correct: "10",
    answers: {
      1: "00",
      2: "11",
      3: "10",
      0: "11",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 2,
  },
  {//"C" TODO: hacer el asset
    correct: "110",
    answers: {
      1: "010",
      2: "110",
      3: "001",
      0: "111",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 0,
  },
],
  3: [{
    correct: "01",
    answers: {
      1: "00",
      2: "10",
      3: "11",
      0: "01",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 3,
  },
],
  4: [{
    correct: "01",
    answers: {
      1: "10",
      2: "11",
      3: "01",
      0: "00",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 2,
  },
],
  5: [{
    correct: "011",
    answers: {
      1: "111",
      2: "011",
      3: "101",
      0: "010",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 1,
  },
],
  SideR3: [{
    correct: "AND",
    answers: {
      1: "OR",
      2: "AND",
      3: "NOT",
      0: "NINGUNA",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 1,
  },
],
  SideR4: [{
    correct: "AND & NOT",
    answers: {
      1: "OR & NOT",
      2: "AND & OR",
      3: "AND & NOT",
      0: "AND & OR & NOT",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 3,
  },
],
  SideR5: [{
    correct: "OR o XOR",
    answers: {
      1: "NINGUNA",
      2: "OR o NAND",
      3: "XNOR o NAND",
      0: "OR o XOR",
    },
    wrongMappings: {
      1: 1,
      2: 2,
      3: 3,
      0: 0,
    },
    rightMapping: 0,
  },
],
};
