export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    MENU_SCENE: 'MENU_SCENE',
    LEVEL_SCENE: 'LEVEL_SCENE',
    LEVEL_SCENE2: 'LEVEL_SCENE2',
    LEVEL_SCENE3: 'LEVEL_SCENE3',
    LEVEL_SCENE4: 'LEVEL_SCENE4',
    LEVEL_SCENE5: 'LEVEL_SCENE5',
    SIDE_ROOM: 'SIDE_ROOM',
    INTRO_SCENE: 'INTRO_SCENE',
    GAMEOVER_SCENE: 'GAMEOVER_SCENE',
    PROGRESS_SCENE: 'PROGRESS_SCENE',
    END_SCENE: 'END_SCENE',
})